(() => {
  const lessons = [
  { id: "hanzi_lai_surname", category: "hanzi", display: "賴", hint: "ㄌㄞˋ", pinyin: "lài", meaning: "surname Lai", speakText: "賴", lang: "zh-TW" },
  { id: "hanzi_pin", category: "hanzi", display: "品", hint: "ㄆㄧㄣˇ", pinyin: "pǐn", meaning: "item / character", speakText: "品", lang: "zh-TW" },
  { id: "hanzi_wei_jade", category: "hanzi", display: "瑋", hint: "ㄨㄟˇ", pinyin: "wěi", meaning: "precious jade / name", speakText: "瑋", lang: "zh-TW" },
  { id: "hanzi_an", category: "hanzi", display: "安", hint: "ㄢ", pinyin: "ān", meaning: "safe / peace", speakText: "安", lang: "zh-TW" },
  { id: "hanzi_lin_forest", category: "hanzi", display: "林", hint: "ㄌㄧㄣˊ", pinyin: "lín", meaning: "woods / forest", speakText: "林", lang: "zh-TW" },
  { id: "hanzi_wei_power", category: "hanzi", display: "威", hint: "ㄨㄟ", pinyin: "wēi", meaning: "power / dignity / name", speakText: "威", lang: "zh-TW" },
  { id: "hanzi_xun_merit", category: "hanzi", display: "勳", hint: "ㄒㄩㄣ", pinyin: "xūn", meaning: "merit / honor / name", speakText: "勳", lang: "zh-TW" },
  { id: "hanzi_wo", category: "hanzi", display: "我", hint: "ㄨㄛˇ", meaning: "I / me", speakText: "我", lang: "zh-TW" },
  { id: "hanzi_ni", category: "hanzi", display: "你", hint: "ㄋㄧˇ", meaning: "you", speakText: "你", lang: "zh-TW" },
  { id: "hanzi_ta_m", category: "hanzi", display: "他", hint: "ㄊㄚ", meaning: "he", speakText: "他", lang: "zh-TW" },
  { id: "hanzi_ta_f", category: "hanzi", display: "她", hint: "ㄊㄚ", meaning: "she", speakText: "她", lang: "zh-TW" },
  { id: "hanzi_shi", category: "hanzi", display: "是", hint: "ㄕˋ", meaning: "to be", speakText: "是", lang: "zh-TW" },
  { id: "hanzi_bu", category: "hanzi", display: "不", hint: "ㄅㄨˋ", meaning: "not", speakText: "不", lang: "zh-TW" },
  { id: "hanzi_you", category: "hanzi", display: "有", hint: "ㄧㄡˇ", meaning: "have", speakText: "有", lang: "zh-TW" },
  { id: "hanzi_zai", category: "hanzi", display: "在", hint: "ㄗㄞˋ", meaning: "at / in", speakText: "在", lang: "zh-TW" },
  { id: "hanzi_ren", category: "hanzi", display: "人", hint: "ㄖㄣˊ", meaning: "person", speakText: "人", lang: "zh-TW" },
  { id: "hanzi_da", category: "hanzi", display: "大", hint: "ㄉㄚˋ", meaning: "big", speakText: "大", lang: "zh-TW" },
  { id: "hanzi_xiao", category: "hanzi", display: "小", hint: "ㄒㄧㄠˇ", meaning: "small", speakText: "小", lang: "zh-TW" },
  { id: "hanzi_shang", category: "hanzi", display: "上", hint: "ㄕㄤˋ", meaning: "up", speakText: "上", lang: "zh-TW" },
  { id: "hanzi_xia", category: "hanzi", display: "下", hint: "ㄒㄧㄚˋ", meaning: "down", speakText: "下", lang: "zh-TW" },
  { id: "hanzi_zhong", category: "hanzi", display: "中", hint: "ㄓㄨㄥ", meaning: "middle", speakText: "中", lang: "zh-TW" },
  { id: "hanzi_tian", category: "hanzi", display: "天", hint: "ㄊㄧㄢ", meaning: "sky / day", speakText: "天", lang: "zh-TW" },
  { id: "hanzi_di", category: "hanzi", display: "地", hint: "ㄉㄧˋ", meaning: "ground", speakText: "地", lang: "zh-TW" },
  { id: "hanzi_ri", category: "hanzi", display: "日", hint: "ㄖˋ", meaning: "sun / day", speakText: "日", lang: "zh-TW" },
  { id: "hanzi_yue", category: "hanzi", display: "月", hint: "ㄩㄝˋ", meaning: "moon / month", speakText: "月", lang: "zh-TW" },
  { id: "hanzi_shan", category: "hanzi", display: "山", hint: "ㄕㄢ", meaning: "mountain", speakText: "山", lang: "zh-TW" },
  { id: "hanzi_shui", category: "hanzi", display: "水", hint: "ㄕㄨㄟˇ", meaning: "water", speakText: "水", lang: "zh-TW" },
  { id: "hanzi_huo", category: "hanzi", display: "火", hint: "ㄏㄨㄛˇ", meaning: "fire", speakText: "火", lang: "zh-TW" },
  { id: "hanzi_mu", category: "hanzi", display: "木", hint: "ㄇㄨˋ", meaning: "wood / tree", speakText: "木", lang: "zh-TW" },
  { id: "hanzi_tu", category: "hanzi", display: "土", hint: "ㄊㄨˇ", meaning: "soil", speakText: "土", lang: "zh-TW" },
  { id: "hanzi_jin", category: "hanzi", display: "金", hint: "ㄐㄧㄣ", meaning: "gold / metal", speakText: "金", lang: "zh-TW" },
  { id: "hanzi_kou", category: "hanzi", display: "口", hint: "ㄎㄡˇ", meaning: "mouth", speakText: "口", lang: "zh-TW" },
  { id: "hanzi_shou", category: "hanzi", display: "手", hint: "ㄕㄡˇ", meaning: "hand", speakText: "手", lang: "zh-TW" },
  { id: "hanzi_mu_eye", category: "hanzi", display: "目", hint: "ㄇㄨˋ", meaning: "eye", speakText: "目", lang: "zh-TW" },
  { id: "hanzi_er", category: "hanzi", display: "耳", hint: "ㄦˇ", meaning: "ear", speakText: "耳", lang: "zh-TW" },
  { id: "hanzi_zu", category: "hanzi", display: "足", hint: "ㄗㄨˊ", meaning: "foot", speakText: "足", lang: "zh-TW" },
  { id: "hanzi_xin", category: "hanzi", display: "心", hint: "ㄒㄧㄣ", meaning: "heart", speakText: "心", lang: "zh-TW" },
  { id: "hanzi_men", category: "hanzi", display: "門", hint: "ㄇㄣˊ", meaning: "door", speakText: "門", lang: "zh-TW" },
  { id: "hanzi_che", category: "hanzi", display: "車", hint: "ㄔㄜ", meaning: "car", speakText: "車", lang: "zh-TW" },
  { id: "hanzi_ma", category: "hanzi", display: "馬", hint: "ㄇㄚˇ", meaning: "horse", speakText: "馬", lang: "zh-TW" },
  { id: "hanzi_niao", category: "hanzi", display: "鳥", hint: "ㄋㄧㄠˇ", meaning: "bird", speakText: "鳥", lang: "zh-TW" },
  { id: "hanzi_yu_fish", category: "hanzi", display: "魚", hint: "ㄩˊ", meaning: "fish", speakText: "魚", lang: "zh-TW" },
  { id: "hanzi_chong", category: "hanzi", display: "蟲", hint: "ㄔㄨㄥˊ", meaning: "bug", speakText: "蟲", lang: "zh-TW" },
  { id: "hanzi_hua", category: "hanzi", display: "花", hint: "ㄏㄨㄚ", meaning: "flower", speakText: "花", lang: "zh-TW" },
  { id: "hanzi_cao", category: "hanzi", display: "草", hint: "ㄘㄠˇ", meaning: "grass", speakText: "草", lang: "zh-TW" },
  { id: "hanzi_mi", category: "hanzi", display: "米", hint: "ㄇㄧˇ", meaning: "rice", speakText: "米", lang: "zh-TW" },
  { id: "hanzi_fan", category: "hanzi", display: "飯", hint: "ㄈㄢˋ", meaning: "meal / rice", speakText: "飯", lang: "zh-TW" },
  { id: "hanzi_guo", category: "hanzi", display: "果", hint: "ㄍㄨㄛˇ", meaning: "fruit", speakText: "果", lang: "zh-TW" },
  { id: "hanzi_ai", category: "hanzi", display: "愛", hint: "ㄞˋ", meaning: "love", speakText: "愛", lang: "zh-TW" },
  { id: "hanzi_hao", category: "hanzi", display: "好", hint: "ㄏㄠˇ", meaning: "good", speakText: "好", lang: "zh-TW" },
  { id: "hanzi_lai", category: "hanzi", display: "來", hint: "ㄌㄞˊ", meaning: "come", speakText: "來", lang: "zh-TW" },
  { id: "hanzi_qu", category: "hanzi", display: "去", hint: "ㄑㄩˋ", meaning: "go", speakText: "去", lang: "zh-TW" },
  { id: "hanzi_kan", category: "hanzi", display: "看", hint: "ㄎㄢˋ", meaning: "look", speakText: "看", lang: "zh-TW" },
  { id: "hanzi_ting", category: "hanzi", display: "聽", hint: "ㄊㄧㄥ", meaning: "listen", speakText: "聽", lang: "zh-TW" },
  { id: "hanzi_shuo", category: "hanzi", display: "說", hint: "ㄕㄨㄛ", meaning: "speak", speakText: "說", lang: "zh-TW" },
  { id: "hanzi_xie", category: "hanzi", display: "寫", hint: "ㄒㄧㄝˇ", meaning: "write", speakText: "寫", lang: "zh-TW" },
  { id: "hanzi_du", category: "hanzi", display: "讀", hint: "ㄉㄨˊ", meaning: "read", speakText: "讀", lang: "zh-TW" },
  { id: "hanzi_xue", category: "hanzi", display: "學", hint: "ㄒㄩㄝˊ", meaning: "learn", speakText: "學", lang: "zh-TW" },
  { id: "hanzi_wen", category: "hanzi", display: "問", hint: "ㄨㄣˋ", meaning: "ask", speakText: "問", lang: "zh-TW" },
  { id: "hanzi_xiao_school", category: "hanzi", display: "校", hint: "ㄒㄧㄠˋ", meaning: "school", speakText: "校", lang: "zh-TW" },
  { id: "hanzi_jia", category: "hanzi", display: "家", hint: "ㄐㄧㄚ", meaning: "home", speakText: "家", lang: "zh-TW" },
  { id: "hanzi_ba", category: "hanzi", display: "爸", hint: "ㄅㄚˋ", meaning: "dad", speakText: "爸", lang: "zh-TW" },
  { id: "hanzi_ma_mom", category: "hanzi", display: "媽", hint: "ㄇㄚ", meaning: "mom", speakText: "媽", lang: "zh-TW" },
  { id: "hanzi_ge", category: "hanzi", display: "哥", hint: "ㄍㄜ", meaning: "older brother", speakText: "哥", lang: "zh-TW" },
  { id: "hanzi_jie", category: "hanzi", display: "姐", hint: "ㄐㄧㄝˇ", meaning: "older sister", speakText: "姐", lang: "zh-TW" },
  { id: "hanzi_di_bro", category: "hanzi", display: "弟", hint: "ㄉㄧˋ", meaning: "younger brother", speakText: "弟", lang: "zh-TW" },
  { id: "hanzi_mei", category: "hanzi", display: "妹", hint: "ㄇㄟˋ", meaning: "younger sister", speakText: "妹", lang: "zh-TW" },
  { id: "hanzi_peng", category: "hanzi", display: "朋", hint: "ㄆㄥˊ", meaning: "friend part", speakText: "朋", lang: "zh-TW" },
  { id: "hanzi_you_friend", category: "hanzi", display: "友", hint: "ㄧㄡˇ", meaning: "friend", speakText: "友", lang: "zh-TW" },
  { id: "hanzi_nian", category: "hanzi", display: "年", hint: "ㄋㄧㄢˊ", meaning: "year", speakText: "年", lang: "zh-TW" },
  { id: "hanzi_jin_today", category: "hanzi", display: "今", hint: "ㄐㄧㄣ", meaning: "today part", speakText: "今", lang: "zh-TW" },
  { id: "hanzi_ming", category: "hanzi", display: "明", hint: "ㄇㄧㄥˊ", meaning: "bright / tomorrow part", speakText: "明", lang: "zh-TW" },
  { id: "hanzi_zao", category: "hanzi", display: "早", hint: "ㄗㄠˇ", meaning: "morning", speakText: "早", lang: "zh-TW" },
  { id: "hanzi_wan", category: "hanzi", display: "晚", hint: "ㄨㄢˇ", meaning: "evening", speakText: "晚", lang: "zh-TW" },
  { id: "hanzi_qi", category: "hanzi", display: "七", hint: "ㄑㄧ", meaning: "seven", speakText: "七", lang: "zh-TW" },
  { id: "hanzi_yi", category: "hanzi", display: "一", hint: "ㄧ", meaning: "one", speakText: "一", lang: "zh-TW" },
  { id: "hanzi_er_two", category: "hanzi", display: "二", hint: "ㄦˋ", meaning: "two", speakText: "二", lang: "zh-TW" },
  { id: "hanzi_san", category: "hanzi", display: "三", hint: "ㄙㄢ", meaning: "three", speakText: "三", lang: "zh-TW" },
  { id: "hanzi_si", category: "hanzi", display: "四", hint: "ㄙˋ", meaning: "four", speakText: "四", lang: "zh-TW" },
  { id: "hanzi_wu", category: "hanzi", display: "五", hint: "ㄨˇ", meaning: "five", speakText: "五", lang: "zh-TW" },
  { id: "hanzi_liu", category: "hanzi", display: "六", hint: "ㄌㄧㄡˋ", meaning: "six", speakText: "六", lang: "zh-TW" },
  { id: "hanzi_ba_eight", category: "hanzi", display: "八", hint: "ㄅㄚ", meaning: "eight", speakText: "八", lang: "zh-TW" },
  { id: "hanzi_jiu", category: "hanzi", display: "九", hint: "ㄐㄧㄡˇ", meaning: "nine", speakText: "九", lang: "zh-TW" },
  { id: "hanzi_shi_ten", category: "hanzi", display: "十", hint: "ㄕˊ", meaning: "ten", speakText: "十", lang: "zh-TW" },
  { id: "hanzi_bai", category: "hanzi", display: "百", hint: "ㄅㄞˇ", meaning: "hundred", speakText: "百", lang: "zh-TW" },
  { id: "hanzi_qian", category: "hanzi", display: "千", hint: "ㄑㄧㄢ", meaning: "thousand", speakText: "千", lang: "zh-TW" },
  { id: "hanzi_duo", category: "hanzi", display: "多", hint: "ㄉㄨㄛ", meaning: "many", speakText: "多", lang: "zh-TW" },
  { id: "hanzi_shao", category: "hanzi", display: "少", hint: "ㄕㄠˇ", meaning: "few", speakText: "少", lang: "zh-TW" },
  { id: "hanzi_chang", category: "hanzi", display: "長", hint: "ㄔㄤˊ", meaning: "long", speakText: "長", lang: "zh-TW" },
  { id: "hanzi_duan", category: "hanzi", display: "短", hint: "ㄉㄨㄢˇ", meaning: "short", speakText: "短", lang: "zh-TW" },
  { id: "hanzi_gao", category: "hanzi", display: "高", hint: "ㄍㄠ", meaning: "tall", speakText: "高", lang: "zh-TW" },
  { id: "hanzi_di_low", category: "hanzi", display: "低", hint: "ㄉㄧ", meaning: "low", speakText: "低", lang: "zh-TW" },
  { id: "hanzi_hong", category: "hanzi", display: "紅", hint: "ㄏㄨㄥˊ", meaning: "red", speakText: "紅", lang: "zh-TW" },
  { id: "hanzi_bai_white", category: "hanzi", display: "白", hint: "ㄅㄞˊ", meaning: "white", speakText: "白", lang: "zh-TW" },
  { id: "hanzi_he_black", category: "hanzi", display: "黑", hint: "ㄏㄟ", meaning: "black", speakText: "黑", lang: "zh-TW" },
  { id: "hanzi_lan", category: "hanzi", display: "藍", hint: "ㄌㄢˊ", meaning: "blue", speakText: "藍", lang: "zh-TW" },
  { id: "hanzi_lv", category: "hanzi", display: "綠", hint: "ㄌㄩˋ", meaning: "green", speakText: "綠", lang: "zh-TW" },
  { id: "hanzi_yu_rain", category: "hanzi", display: "雨", hint: "ㄩˇ", meaning: "rain", speakText: "雨", lang: "zh-TW" },
  { id: "hanzi_feng", category: "hanzi", display: "風", hint: "ㄈㄥ", meaning: "wind", speakText: "風", lang: "zh-TW" },
  { id: "hanzi_yun_cloud", category: "hanzi", display: "雲", hint: "ㄩㄣˊ", pinyin: "yún", meaning: "cloud", speakText: "雲", lang: "zh-TW" },
  { id: "hanzi_que", category: "hanzi", display: "確", hint: "ㄑㄩㄝˋ", pinyin: "què", meaning: "certain / correct", speakText: "確", lang: "zh-TW" },
  { id: "hanzi_ding", category: "hanzi", display: "定", hint: "ㄉㄧㄥˋ", pinyin: "dìng", meaning: "decide / set", speakText: "定", lang: "zh-TW" },
  { id: "hanzi_zhi", category: "hanzi", display: "知", hint: "ㄓ", pinyin: "zhī", meaning: "know", speakText: "知", lang: "zh-TW" },
  { id: "hanzi_dao_way", category: "hanzi", display: "道", hint: "ㄉㄠˋ", pinyin: "dào", meaning: "way / road", speakText: "道", lang: "zh-TW" },
  { id: "hanzi_ming_name", category: "hanzi", display: "名", hint: "ㄇㄧㄥˊ", pinyin: "míng", meaning: "name", speakText: "名", lang: "zh-TW" },
  { id: "hanzi_zi", category: "hanzi", display: "字", hint: "ㄗˋ", pinyin: "zì", meaning: "character / word", speakText: "字", lang: "zh-TW" },
  { id: "hanzi_ke", category: "hanzi", display: "課", hint: "ㄎㄜˋ", pinyin: "kè", meaning: "lesson / class", speakText: "課", lang: "zh-TW" },
  { id: "hanzi_shu", category: "hanzi", display: "書", hint: "ㄕㄨ", pinyin: "shū", meaning: "book", speakText: "書", lang: "zh-TW" },
  { id: "hanzi_ben", category: "hanzi", display: "本", hint: "ㄅㄣˇ", pinyin: "běn", meaning: "book / root", speakText: "本", lang: "zh-TW" },
  { id: "hanzi_bi", category: "hanzi", display: "筆", hint: "ㄅㄧˇ", pinyin: "bǐ", meaning: "pen / pencil", speakText: "筆", lang: "zh-TW" },
  { id: "hanzi_zhi_paper", category: "hanzi", display: "紙", hint: "ㄓˇ", pinyin: "zhǐ", meaning: "paper", speakText: "紙", lang: "zh-TW" },
  { id: "hanzi_zhuo", category: "hanzi", display: "桌", hint: "ㄓㄨㄛ", pinyin: "zhuō", meaning: "table / desk", speakText: "桌", lang: "zh-TW" },
  { id: "hanzi_yi_chair", category: "hanzi", display: "椅", hint: "ㄧˇ", pinyin: "yǐ", meaning: "chair", speakText: "椅", lang: "zh-TW" },
  { id: "hanzi_qian_front", category: "hanzi", display: "前", hint: "ㄑㄧㄢˊ", pinyin: "qián", meaning: "front / before", speakText: "前", lang: "zh-TW" },
  { id: "hanzi_hou", category: "hanzi", display: "後", hint: "ㄏㄡˋ", pinyin: "hòu", meaning: "back / after", speakText: "後", lang: "zh-TW" },
  { id: "hanzi_zuo_left", category: "hanzi", display: "左", hint: "ㄗㄨㄛˇ", pinyin: "zuǒ", meaning: "left", speakText: "左", lang: "zh-TW" },
  { id: "hanzi_you_right", category: "hanzi", display: "右", hint: "ㄧㄡˋ", pinyin: "yòu", meaning: "right", speakText: "右", lang: "zh-TW" },
  { id: "hanzi_li", category: "hanzi", display: "裡", hint: "ㄌㄧˇ", pinyin: "lǐ", meaning: "inside", speakText: "裡", lang: "zh-TW" },
  { id: "hanzi_wai", category: "hanzi", display: "外", hint: "ㄨㄞˋ", pinyin: "wài", meaning: "outside", speakText: "外", lang: "zh-TW" },
  { id: "hanzi_nan", category: "hanzi", display: "男", hint: "ㄋㄢˊ", pinyin: "nán", meaning: "boy / male", speakText: "男", lang: "zh-TW" },
  { id: "hanzi_nv", category: "hanzi", display: "女", hint: "ㄋㄩˇ", pinyin: "nǚ", meaning: "girl / female", speakText: "女", lang: "zh-TW" },
  { id: "hanzi_zi_child", category: "hanzi", display: "子", hint: "ㄗˇ", pinyin: "zǐ", meaning: "child / son", speakText: "子", lang: "zh-TW" },
  { id: "hanzi_er_child", category: "hanzi", display: "兒", hint: "ㄦˊ", pinyin: "ér", meaning: "child", speakText: "兒", lang: "zh-TW" },
  { id: "hanzi_laoshi_lao", category: "hanzi", display: "老", hint: "ㄌㄠˇ", pinyin: "lǎo", meaning: "old / teacher part", speakText: "老", lang: "zh-TW" },
  { id: "hanzi_shi_teacher", category: "hanzi", display: "師", hint: "ㄕ", pinyin: "shī", meaning: "teacher", speakText: "師", lang: "zh-TW" },
  { id: "hanzi_sheng", category: "hanzi", display: "生", hint: "ㄕㄥ", pinyin: "shēng", meaning: "life / student part", speakText: "生", lang: "zh-TW" },
  { id: "hanzi_ban", category: "hanzi", display: "班", hint: "ㄅㄢ", pinyin: "bān", meaning: "class", speakText: "班", lang: "zh-TW" },
  { id: "hanzi_tong", category: "hanzi", display: "同", hint: "ㄊㄨㄥˊ", pinyin: "tóng", meaning: "same", speakText: "同", lang: "zh-TW" },
  { id: "hanzi_men_plural", category: "hanzi", display: "們", hint: "ㄇㄣ˙", pinyin: "men", meaning: "plural marker", speakText: "們", lang: "zh-TW" },
  { id: "hanzi_zhe", category: "hanzi", display: "這", hint: "ㄓㄜˋ", pinyin: "zhè", meaning: "this", speakText: "這", lang: "zh-TW" },
  { id: "hanzi_na", category: "hanzi", display: "那", hint: "ㄋㄚˋ", pinyin: "nà", meaning: "that", speakText: "那", lang: "zh-TW" },
  { id: "hanzi_na_which", category: "hanzi", display: "哪", hint: "ㄋㄚˇ", pinyin: "nǎ", meaning: "which", speakText: "哪", lang: "zh-TW" },
  { id: "hanzi_shei", category: "hanzi", display: "誰", hint: "ㄕㄟˊ", pinyin: "shéi", meaning: "who", speakText: "誰", lang: "zh-TW" },
  { id: "hanzi_shen", category: "hanzi", display: "什", hint: "ㄕㄣˊ", pinyin: "shén", meaning: "what part", speakText: "什", lang: "zh-TW" },
  { id: "hanzi_me", category: "hanzi", display: "麼", hint: "ㄇㄜ˙", pinyin: "me", meaning: "what particle", speakText: "麼", lang: "zh-TW" },
  { id: "hanzi_wei_because", category: "hanzi", display: "為", hint: "ㄨㄟˋ", pinyin: "wèi", meaning: "for / because", speakText: "為", lang: "zh-TW" },
  { id: "hanzi_yin", category: "hanzi", display: "因", hint: "ㄧㄣ", pinyin: "yīn", meaning: "cause", speakText: "因", lang: "zh-TW" },
  { id: "hanzi_suo", category: "hanzi", display: "所", hint: "ㄙㄨㄛˇ", pinyin: "suǒ", meaning: "place / that which", speakText: "所", lang: "zh-TW" },
  { id: "hanzi_yi_also", category: "hanzi", display: "也", hint: "ㄧㄝˇ", pinyin: "yě", meaning: "also", speakText: "也", lang: "zh-TW" },
  { id: "hanzi_dou", category: "hanzi", display: "都", hint: "ㄉㄡ", pinyin: "dōu", meaning: "all", speakText: "都", lang: "zh-TW" },
  { id: "hanzi_hen", category: "hanzi", display: "很", hint: "ㄏㄣˇ", pinyin: "hěn", meaning: "very", speakText: "很", lang: "zh-TW" },
  { id: "hanzi_zhen", category: "hanzi", display: "真", hint: "ㄓㄣ", pinyin: "zhēn", meaning: "true / really", speakText: "真", lang: "zh-TW" },
  { id: "hanzi_xiang", category: "hanzi", display: "想", hint: "ㄒㄧㄤˇ", pinyin: "xiǎng", meaning: "think / want", speakText: "想", lang: "zh-TW" },
  { id: "hanzi_yao", category: "hanzi", display: "要", hint: "ㄧㄠˋ", pinyin: "yào", meaning: "want / need", speakText: "要", lang: "zh-TW" },
  { id: "hanzi_hui", category: "hanzi", display: "會", hint: "ㄏㄨㄟˋ", pinyin: "huì", meaning: "can / will", speakText: "會", lang: "zh-TW" },
  { id: "hanzi_neng", category: "hanzi", display: "能", hint: "ㄋㄥˊ", pinyin: "néng", meaning: "able", speakText: "能", lang: "zh-TW" },
  { id: "hanzi_mai", category: "hanzi", display: "買", hint: "ㄇㄞˇ", pinyin: "mǎi", meaning: "buy", speakText: "買", lang: "zh-TW" },
  { id: "hanzi_mai_sell", category: "hanzi", display: "賣", hint: "ㄇㄞˋ", pinyin: "mài", meaning: "sell", speakText: "賣", lang: "zh-TW" },
  { id: "hanzi_qing", category: "hanzi", display: "請", hint: "ㄑㄧㄥˇ", pinyin: "qǐng", meaning: "please", speakText: "請", lang: "zh-TW" },
  { id: "hanzi_xie_thanks", category: "hanzi", display: "謝", hint: "ㄒㄧㄝˋ", pinyin: "xiè", meaning: "thank", speakText: "謝", lang: "zh-TW" },
  { id: "hanzi_dui", category: "hanzi", display: "對", hint: "ㄉㄨㄟˋ", pinyin: "duì", meaning: "correct / toward", speakText: "對", lang: "zh-TW" },
  { id: "hanzi_cuo", category: "hanzi", display: "錯", hint: "ㄘㄨㄛˋ", pinyin: "cuò", meaning: "wrong", speakText: "錯", lang: "zh-TW" },
  { id: "hanzi_kai", category: "hanzi", display: "開", hint: "ㄎㄞ", pinyin: "kāi", meaning: "open", speakText: "開", lang: "zh-TW" },
  { id: "hanzi_guan", category: "hanzi", display: "關", hint: "ㄍㄨㄢ", pinyin: "guān", meaning: "close", speakText: "關", lang: "zh-TW" },
  { id: "hanzi_xin_new", category: "hanzi", display: "新", hint: "ㄒㄧㄣ", pinyin: "xīn", meaning: "new", speakText: "新", lang: "zh-TW" },
  { id: "hanzi_jiu_old", category: "hanzi", display: "舊", hint: "ㄐㄧㄡˋ", pinyin: "jiù", meaning: "old", speakText: "舊", lang: "zh-TW" },
  { id: "hanzi_fen", category: "hanzi", display: "分", hint: "ㄈㄣ", pinyin: "fēn", meaning: "divide / minute", speakText: "分", lang: "zh-TW" },
  { id: "hanzi_wu_noon", category: "hanzi", display: "午", hint: "ㄨˇ", pinyin: "wǔ", meaning: "noon", speakText: "午", lang: "zh-TW" },
  { id: "hanzi_shi_time", category: "hanzi", display: "時", hint: "ㄕˊ", pinyin: "shí", meaning: "time / hour", speakText: "時", lang: "zh-TW" },
  { id: "hanzi_guo_country", category: "hanzi", display: "國", hint: "ㄍㄨㄛˊ", pinyin: "guó", meaning: "country", speakText: "國", lang: "zh-TW" },
  { id: "hanzi_yu_language", category: "hanzi", display: "語", hint: "ㄩˇ", pinyin: "yǔ", meaning: "language", speakText: "語", lang: "zh-TW" },
  { id: "hanzi_ying", category: "hanzi", display: "英", hint: "ㄧㄥ", pinyin: "yīng", meaning: "English / brave", speakText: "英", lang: "zh-TW" },
  { id: "hanzi_wen_text", category: "hanzi", display: "文", hint: "ㄨㄣˊ", pinyin: "wén", meaning: "writing / text", speakText: "文", lang: "zh-TW" },
  { id: "hanzi_shu_math", category: "hanzi", display: "數", hint: "ㄕㄨˋ", pinyin: "shù", meaning: "number / math", speakText: "數", lang: "zh-TW" },
  { id: "hanzi_suan", category: "hanzi", display: "算", hint: "ㄙㄨㄢˋ", pinyin: "suàn", meaning: "calculate", speakText: "算", lang: "zh-TW" },
  { id: "hanzi_ti_question", category: "hanzi", display: "題", hint: "ㄊㄧˊ", pinyin: "tí", meaning: "question / topic", speakText: "題", lang: "zh-TW" },
  { id: "hanzi_da_answer", category: "hanzi", display: "答", hint: "ㄉㄚˊ", pinyin: "dá", meaning: "answer", speakText: "答", lang: "zh-TW" },
  { id: "hanzi_zuo_do", category: "hanzi", display: "作", hint: "ㄗㄨㄛˋ", pinyin: "zuò", meaning: "do / make", speakText: "作", lang: "zh-TW" },
  { id: "hanzi_ye_work", category: "hanzi", display: "業", hint: "ㄧㄝˋ", pinyin: "yè", meaning: "work / homework part", speakText: "業", lang: "zh-TW" },
  { id: "hanzi_yuan_garden", category: "hanzi", display: "園", hint: "ㄩㄢˊ", pinyin: "yuán", meaning: "garden / park", speakText: "園", lang: "zh-TW" },
  { id: "hanzi_tong_child", category: "hanzi", display: "童", hint: "ㄊㄨㄥˊ", pinyin: "tóng", meaning: "child", speakText: "童", lang: "zh-TW" },
  { id: "hanzi_wu_thing", category: "hanzi", display: "物", hint: "ㄨˋ", pinyin: "wù", meaning: "thing / object", speakText: "物", lang: "zh-TW" },
  { id: "hanzi_dian_electric", category: "hanzi", display: "電", hint: "ㄉㄧㄢˋ", pinyin: "diàn", meaning: "electricity", speakText: "電", lang: "zh-TW" },
  { id: "hanzi_nao", category: "hanzi", display: "腦", hint: "ㄋㄠˇ", pinyin: "nǎo", meaning: "brain", speakText: "腦", lang: "zh-TW" },
  { id: "hanzi_hua_phone", category: "hanzi", display: "話", hint: "ㄏㄨㄚˋ", pinyin: "huà", meaning: "speech / phone part", speakText: "話", lang: "zh-TW" },
  { id: "hanzi_ji_machine", category: "hanzi", display: "機", hint: "ㄐㄧ", pinyin: "jī", meaning: "machine", speakText: "機", lang: "zh-TW" },
  { id: "hanzi_lu_road", category: "hanzi", display: "路", hint: "ㄌㄨˋ", pinyin: "lù", meaning: "road", speakText: "路", lang: "zh-TW" },
  { id: "hanzi_jie_street", category: "hanzi", display: "街", hint: "ㄐㄧㄝ", pinyin: "jiē", meaning: "street", speakText: "街", lang: "zh-TW" },
  { id: "hanzi_shi_city", category: "hanzi", display: "市", hint: "ㄕˋ", pinyin: "shì", meaning: "city / market", speakText: "市", lang: "zh-TW" },
  { id: "hanzi_dian_store", category: "hanzi", display: "店", hint: "ㄉㄧㄢˋ", pinyin: "diàn", meaning: "shop / store", speakText: "店", lang: "zh-TW" },
  { id: "hanzi_qian_money", category: "hanzi", display: "錢", hint: "ㄑㄧㄢˊ", pinyin: "qián", meaning: "money", speakText: "錢", lang: "zh-TW" },
  { id: "hanzi_yuan_money", category: "hanzi", display: "元", hint: "ㄩㄢˊ", pinyin: "yuán", meaning: "dollar / yuan", speakText: "元", lang: "zh-TW" },
  { id: "hanzi_jiao", category: "hanzi", display: "角", hint: "ㄐㄧㄠˇ", pinyin: "jiǎo", meaning: "corner / dime", speakText: "角", lang: "zh-TW" },
  { id: "hanzi_dian_point", category: "hanzi", display: "點", hint: "ㄉㄧㄢˇ", pinyin: "diǎn", meaning: "point / o'clock", speakText: "點", lang: "zh-TW" },
  { id: "hanzi_sui_age", category: "hanzi", display: "歲", hint: "ㄙㄨㄟˋ", pinyin: "suì", meaning: "years old", speakText: "歲", lang: "zh-TW" },
  { id: "hanzi_zhu_live", category: "hanzi", display: "住", hint: "ㄓㄨˋ", pinyin: "zhù", meaning: "live / stay", speakText: "住", lang: "zh-TW" },
  { id: "hanzi_zuo_sit", category: "hanzi", display: "坐", hint: "ㄗㄨㄛˋ", pinyin: "zuò", meaning: "sit", speakText: "坐", lang: "zh-TW" },
  { id: "hanzi_zhan", category: "hanzi", display: "站", hint: "ㄓㄢˋ", pinyin: "zhàn", meaning: "stand / station", speakText: "站", lang: "zh-TW" },
  { id: "hanzi_zou", category: "hanzi", display: "走", hint: "ㄗㄡˇ", pinyin: "zǒu", meaning: "walk / go", speakText: "走", lang: "zh-TW" },
  { id: "hanzi_pao", category: "hanzi", display: "跑", hint: "ㄆㄠˇ", pinyin: "pǎo", meaning: "run", speakText: "跑", lang: "zh-TW" },
  { id: "hanzi_tiao", category: "hanzi", display: "跳", hint: "ㄊㄧㄠˋ", pinyin: "tiào", meaning: "jump", speakText: "跳", lang: "zh-TW" },
  { id: "hanzi_xiao_laugh", category: "hanzi", display: "笑", hint: "ㄒㄧㄠˋ", pinyin: "xiào", meaning: "smile / laugh", speakText: "笑", lang: "zh-TW" },
  { id: "hanzi_ku", category: "hanzi", display: "哭", hint: "ㄎㄨ", pinyin: "kū", meaning: "cry", speakText: "哭", lang: "zh-TW" },
  { id: "hanzi_xi", category: "hanzi", display: "喜", hint: "ㄒㄧˇ", pinyin: "xǐ", meaning: "happy / like", speakText: "喜", lang: "zh-TW" },
  { id: "hanzi_huan", category: "hanzi", display: "歡", hint: "ㄏㄨㄢ", pinyin: "huān", meaning: "joy / like part", speakText: "歡", lang: "zh-TW" },
  { id: "hanzi_pa", category: "hanzi", display: "怕", hint: "ㄆㄚˋ", pinyin: "pà", meaning: "afraid", speakText: "怕", lang: "zh-TW" },
  { id: "hanzi_qi_air", category: "hanzi", display: "氣", hint: "ㄑㄧˋ", pinyin: "qì", meaning: "air / mood", speakText: "氣", lang: "zh-TW" },
  { id: "hanzi_leng", category: "hanzi", display: "冷", hint: "ㄌㄥˇ", pinyin: "lěng", meaning: "cold", speakText: "冷", lang: "zh-TW" },
  { id: "hanzi_nuan", category: "hanzi", display: "暖", hint: "ㄋㄨㄢˇ", pinyin: "nuǎn", meaning: "warm", speakText: "暖", lang: "zh-TW" },
  { id: "hanzi_liang_bright", category: "hanzi", display: "亮", hint: "ㄌㄧㄤˋ", pinyin: "liàng", meaning: "bright", speakText: "亮", lang: "zh-TW" },
  { id: "hanzi_an_dark", category: "hanzi", display: "暗", hint: "ㄢˋ", pinyin: "àn", meaning: "dark", speakText: "暗", lang: "zh-TW" },
  { id: "hanzi_xing_star", category: "hanzi", display: "星", hint: "ㄒㄧㄥ", pinyin: "xīng", meaning: "star", speakText: "星", lang: "zh-TW" },
  { id: "hanzi_kong_sky", category: "hanzi", display: "空", hint: "ㄎㄨㄥ", pinyin: "kōng", meaning: "sky / empty", speakText: "空", lang: "zh-TW" },
  { id: "hanzi_hai_sea", category: "hanzi", display: "海", hint: "ㄏㄞˇ", pinyin: "hǎi", meaning: "sea", speakText: "海", lang: "zh-TW" },
  { id: "hanzi_he_river", category: "hanzi", display: "河", hint: "ㄏㄜˊ", pinyin: "hé", meaning: "river", speakText: "河", lang: "zh-TW" },
  { id: "hanzi_common_001", category: "hanzi", display: "可", hint: "ㄎㄜˇ", pinyin: "kě", meaning: "can / may", speakText: "可", lang: "zh-TW" },
  { id: "hanzi_common_002", category: "hanzi", display: "沒", hint: "ㄇㄟˊ", pinyin: "méi", meaning: "not have / no", speakText: "沒", lang: "zh-TW" },
  { id: "hanzi_common_003", category: "hanzi", display: "個", hint: "ㄍㄜˋ", pinyin: "gè", meaning: "individual measure word", speakText: "個", lang: "zh-TW" },
  { id: "hanzi_common_004", category: "hanzi", display: "得", hint: "ㄉㄜˊ", pinyin: "dé", meaning: "get / must", speakText: "得", lang: "zh-TW" },
  { id: "hanzi_common_005", category: "hanzi", display: "著", hint: "ㄓㄜ˙", pinyin: "zhe", meaning: "action particle", speakText: "著", lang: "zh-TW" },
  { id: "hanzi_common_006", category: "hanzi", display: "只", hint: "ㄓˇ", pinyin: "zhǐ", meaning: "only", speakText: "只", lang: "zh-TW" },
  { id: "hanzi_common_007", category: "hanzi", display: "就", hint: "ㄐㄧㄡˋ", pinyin: "jiù", meaning: "then / right away", speakText: "就", lang: "zh-TW" },
  { id: "hanzi_common_008", category: "hanzi", display: "還", hint: "ㄏㄞˊ", pinyin: "hái", meaning: "still / also", speakText: "還", lang: "zh-TW" },
  { id: "hanzi_common_009", category: "hanzi", display: "但", hint: "ㄉㄢˋ", pinyin: "dàn", meaning: "but", speakText: "但", lang: "zh-TW" },
  { id: "hanzi_common_010", category: "hanzi", display: "比", hint: "ㄅㄧˇ", pinyin: "bǐ", meaning: "compare", speakText: "比", lang: "zh-TW" },
  { id: "hanzi_common_011", category: "hanzi", display: "最", hint: "ㄗㄨㄟˋ", pinyin: "zuì", meaning: "most", speakText: "最", lang: "zh-TW" },
  { id: "hanzi_common_012", category: "hanzi", display: "再", hint: "ㄗㄞˋ", pinyin: "zài", meaning: "again", speakText: "再", lang: "zh-TW" },
  { id: "hanzi_common_013", category: "hanzi", display: "從", hint: "ㄘㄨㄥˊ", pinyin: "cóng", meaning: "from", speakText: "從", lang: "zh-TW" },
  { id: "hanzi_common_014", category: "hanzi", display: "向", hint: "ㄒㄧㄤˋ", pinyin: "xiàng", meaning: "toward", speakText: "向", lang: "zh-TW" },
  { id: "hanzi_common_015", category: "hanzi", display: "被", hint: "ㄅㄟˋ", pinyin: "bèi", meaning: "by / passive marker", speakText: "被", lang: "zh-TW" },
  { id: "hanzi_common_016", category: "hanzi", display: "把", hint: "ㄅㄚˇ", pinyin: "bǎ", meaning: "hold / object marker", speakText: "把", lang: "zh-TW" },
  { id: "hanzi_common_017", category: "hanzi", display: "給", hint: "ㄍㄟˇ", pinyin: "gěi", meaning: "give", speakText: "給", lang: "zh-TW" },
  { id: "hanzi_common_018", category: "hanzi", display: "讓", hint: "ㄖㄤˋ", pinyin: "ràng", meaning: "let / allow", speakText: "讓", lang: "zh-TW" },
  { id: "hanzi_common_019", category: "hanzi", display: "跟", hint: "ㄍㄣ", pinyin: "gēn", meaning: "with / follow", speakText: "跟", lang: "zh-TW" },
  { id: "hanzi_common_020", category: "hanzi", display: "與", hint: "ㄩˇ", pinyin: "yǔ", meaning: "and / with", speakText: "與", lang: "zh-TW" },
  { id: "hanzi_common_021", category: "hanzi", display: "或", hint: "ㄏㄨㄛˋ", pinyin: "huò", meaning: "or", speakText: "或", lang: "zh-TW" },
  { id: "hanzi_common_022", category: "hanzi", display: "而", hint: "ㄦˊ", pinyin: "ér", meaning: "and / yet", speakText: "而", lang: "zh-TW" },
  { id: "hanzi_common_023", category: "hanzi", display: "及", hint: "ㄐㄧˊ", pinyin: "jí", meaning: "and / reach", speakText: "及", lang: "zh-TW" },
  { id: "hanzi_common_024", category: "hanzi", display: "由", hint: "ㄧㄡˊ", pinyin: "yóu", meaning: "from / by", speakText: "由", lang: "zh-TW" },
  { id: "hanzi_common_025", category: "hanzi", display: "於", hint: "ㄩˊ", pinyin: "yú", meaning: "at / in", speakText: "於", lang: "zh-TW" },
  { id: "hanzi_common_026", category: "hanzi", display: "用", hint: "ㄩㄥˋ", pinyin: "yòng", meaning: "use", speakText: "用", lang: "zh-TW" },
  { id: "hanzi_common_027", category: "hanzi", display: "做", hint: "ㄗㄨㄛˋ", pinyin: "zuò", meaning: "do / make", speakText: "做", lang: "zh-TW" },
  { id: "hanzi_common_028", category: "hanzi", display: "事", hint: "ㄕˋ", pinyin: "shì", meaning: "thing / matter", speakText: "事", lang: "zh-TW" },
  { id: "hanzi_common_029", category: "hanzi", display: "情", hint: "ㄑㄧㄥˊ", pinyin: "qíng", meaning: "feeling / situation", speakText: "情", lang: "zh-TW" },
  { id: "hanzi_common_030", category: "hanzi", display: "感", hint: "ㄍㄢˇ", pinyin: "gǎn", meaning: "feel", speakText: "感", lang: "zh-TW" },
  { id: "hanzi_common_031", category: "hanzi", display: "意", hint: "ㄧˋ", pinyin: "yì", meaning: "meaning / idea", speakText: "意", lang: "zh-TW" },
  { id: "hanzi_common_032", category: "hanzi", display: "主", hint: "ㄓㄨˇ", pinyin: "zhǔ", meaning: "main / master", speakText: "主", lang: "zh-TW" },
  { id: "hanzi_common_033", category: "hanzi", display: "客", hint: "ㄎㄜˋ", pinyin: "kè", meaning: "guest", speakText: "客", lang: "zh-TW" },
  { id: "hanzi_common_034", category: "hanzi", display: "親", hint: "ㄑㄧㄣ", pinyin: "qīn", meaning: "parent / close", speakText: "親", lang: "zh-TW" },
  { id: "hanzi_common_035", category: "hanzi", display: "醫", hint: "ㄧ", pinyin: "yī", meaning: "doctor / medicine", speakText: "醫", lang: "zh-TW" },
  { id: "hanzi_common_036", category: "hanzi", display: "教", hint: "ㄐㄧㄠˋ", pinyin: "jiào", meaning: "teach", speakText: "教", lang: "zh-TW" },
  { id: "hanzi_common_037", category: "hanzi", display: "級", hint: "ㄐㄧˊ", pinyin: "jí", meaning: "grade / level", speakText: "級", lang: "zh-TW" },
  { id: "hanzi_common_038", category: "hanzi", display: "科", hint: "ㄎㄜ", pinyin: "kē", meaning: "subject / branch", speakText: "科", lang: "zh-TW" },
  { id: "hanzi_common_039", category: "hanzi", display: "室", hint: "ㄕˋ", pinyin: "shì", meaning: "room", speakText: "室", lang: "zh-TW" },
  { id: "hanzi_common_040", category: "hanzi", display: "場", hint: "ㄔㄤˇ", pinyin: "chǎng", meaning: "place / field", speakText: "場", lang: "zh-TW" },
  { id: "hanzi_common_041", category: "hanzi", display: "館", hint: "ㄍㄨㄢˇ", pinyin: "guǎn", meaning: "hall / building", speakText: "館", lang: "zh-TW" },
  { id: "hanzi_common_042", category: "hanzi", display: "隊", hint: "ㄉㄨㄟˋ", pinyin: "duì", meaning: "team / line", speakText: "隊", lang: "zh-TW" },
  { id: "hanzi_common_043", category: "hanzi", display: "組", hint: "ㄗㄨˇ", pinyin: "zǔ", meaning: "group", speakText: "組", lang: "zh-TW" },
  { id: "hanzi_common_044", category: "hanzi", display: "員", hint: "ㄩㄢˊ", pinyin: "yuán", meaning: "member", speakText: "員", lang: "zh-TW" },
  { id: "hanzi_common_045", category: "hanzi", display: "工", hint: "ㄍㄨㄥ", pinyin: "gōng", meaning: "work", speakText: "工", lang: "zh-TW" },
  { id: "hanzi_common_046", category: "hanzi", display: "司", hint: "ㄙ", pinyin: "sī", meaning: "manage / department", speakText: "司", lang: "zh-TW" },
  { id: "hanzi_common_047", category: "hanzi", display: "旅", hint: "ㄌㄩˇ", pinyin: "lǚ", meaning: "travel", speakText: "旅", lang: "zh-TW" },
  { id: "hanzi_common_048", category: "hanzi", display: "遊", hint: "ㄧㄡˊ", pinyin: "yóu", meaning: "play / travel", speakText: "遊", lang: "zh-TW" },
  { id: "hanzi_common_049", category: "hanzi", display: "戲", hint: "ㄒㄧˋ", pinyin: "xì", meaning: "play / game", speakText: "戲", lang: "zh-TW" },
  { id: "hanzi_common_050", category: "hanzi", display: "太", hint: "ㄊㄞˋ", pinyin: "tài", meaning: "too / very", speakText: "太", lang: "zh-TW" },
  { id: "hanzi_common_051", category: "hanzi", display: "陽", hint: "ㄧㄤˊ", pinyin: "yáng", meaning: "sun / positive", speakText: "陽", lang: "zh-TW" },
  { id: "hanzi_common_052", category: "hanzi", display: "陰", hint: "ㄧㄣ", pinyin: "yīn", meaning: "shade / cloudy", speakText: "陰", lang: "zh-TW" },
  { id: "hanzi_common_053", category: "hanzi", display: "晴", hint: "ㄑㄧㄥˊ", pinyin: "qíng", meaning: "clear weather", speakText: "晴", lang: "zh-TW" },
  { id: "hanzi_common_054", category: "hanzi", display: "雷", hint: "ㄌㄟˊ", pinyin: "léi", meaning: "thunder", speakText: "雷", lang: "zh-TW" },
  { id: "hanzi_common_055", category: "hanzi", display: "雪", hint: "ㄒㄩㄝˇ", pinyin: "xuě", meaning: "snow", speakText: "雪", lang: "zh-TW" },
  { id: "hanzi_common_056", category: "hanzi", display: "春", hint: "ㄔㄨㄣ", pinyin: "chūn", meaning: "spring", speakText: "春", lang: "zh-TW" },
  { id: "hanzi_common_057", category: "hanzi", display: "夏", hint: "ㄒㄧㄚˋ", pinyin: "xià", meaning: "summer", speakText: "夏", lang: "zh-TW" },
  { id: "hanzi_common_058", category: "hanzi", display: "秋", hint: "ㄑㄧㄡ", pinyin: "qiū", meaning: "autumn", speakText: "秋", lang: "zh-TW" },
  { id: "hanzi_common_059", category: "hanzi", display: "冬", hint: "ㄉㄨㄥ", pinyin: "dōng", meaning: "winter", speakText: "冬", lang: "zh-TW" },
  { id: "hanzi_common_060", category: "hanzi", display: "葉", hint: "ㄧㄝˋ", pinyin: "yè", meaning: "leaf", speakText: "葉", lang: "zh-TW" },
  { id: "hanzi_common_061", category: "hanzi", display: "樹", hint: "ㄕㄨˋ", pinyin: "shù", meaning: "tree", speakText: "樹", lang: "zh-TW" },
  { id: "hanzi_common_062", category: "hanzi", display: "根", hint: "ㄍㄣ", pinyin: "gēn", meaning: "root", speakText: "根", lang: "zh-TW" },
  { id: "hanzi_common_063", category: "hanzi", display: "森", hint: "ㄙㄣ", pinyin: "sēn", meaning: "forest", speakText: "森", lang: "zh-TW" },
  { id: "hanzi_common_064", category: "hanzi", display: "石", hint: "ㄕˊ", pinyin: "shí", meaning: "stone", speakText: "石", lang: "zh-TW" },
  { id: "hanzi_common_065", category: "hanzi", display: "沙", hint: "ㄕㄚ", pinyin: "shā", meaning: "sand", speakText: "沙", lang: "zh-TW" },
  { id: "hanzi_common_066", category: "hanzi", display: "泉", hint: "ㄑㄩㄢˊ", pinyin: "quán", meaning: "spring water", speakText: "泉", lang: "zh-TW" },
  { id: "hanzi_common_067", category: "hanzi", display: "池", hint: "ㄔˊ", pinyin: "chí", meaning: "pond", speakText: "池", lang: "zh-TW" },
  { id: "hanzi_common_068", category: "hanzi", display: "島", hint: "ㄉㄠˇ", pinyin: "dǎo", meaning: "island", speakText: "島", lang: "zh-TW" },
  { id: "hanzi_common_069", category: "hanzi", display: "谷", hint: "ㄍㄨˇ", pinyin: "gǔ", meaning: "valley", speakText: "谷", lang: "zh-TW" },
  { id: "hanzi_common_070", category: "hanzi", display: "吃", hint: "ㄔ", pinyin: "chī", meaning: "eat", speakText: "吃", lang: "zh-TW" },
  { id: "hanzi_common_071", category: "hanzi", display: "喝", hint: "ㄏㄜ", pinyin: "hē", meaning: "drink", speakText: "喝", lang: "zh-TW" },
  { id: "hanzi_common_072", category: "hanzi", display: "菜", hint: "ㄘㄞˋ", pinyin: "cài", meaning: "vegetable / dish", speakText: "菜", lang: "zh-TW" },
  { id: "hanzi_common_073", category: "hanzi", display: "肉", hint: "ㄖㄡˋ", pinyin: "ròu", meaning: "meat", speakText: "肉", lang: "zh-TW" },
  { id: "hanzi_common_074", category: "hanzi", display: "牛", hint: "ㄋㄧㄡˊ", pinyin: "niú", meaning: "cow", speakText: "牛", lang: "zh-TW" },
  { id: "hanzi_common_075", category: "hanzi", display: "羊", hint: "ㄧㄤˊ", pinyin: "yáng", meaning: "sheep / goat", speakText: "羊", lang: "zh-TW" },
  { id: "hanzi_common_076", category: "hanzi", display: "雞", hint: "ㄐㄧ", pinyin: "jī", meaning: "chicken", speakText: "雞", lang: "zh-TW" },
  { id: "hanzi_common_077", category: "hanzi", display: "蛋", hint: "ㄉㄢˋ", pinyin: "dàn", meaning: "egg", speakText: "蛋", lang: "zh-TW" },
  { id: "hanzi_common_078", category: "hanzi", display: "奶", hint: "ㄋㄞˇ", pinyin: "nǎi", meaning: "milk", speakText: "奶", lang: "zh-TW" },
  { id: "hanzi_common_079", category: "hanzi", display: "茶", hint: "ㄔㄚˊ", pinyin: "chá", meaning: "tea", speakText: "茶", lang: "zh-TW" },
  { id: "hanzi_common_080", category: "hanzi", display: "湯", hint: "ㄊㄤ", pinyin: "tāng", meaning: "soup", speakText: "湯", lang: "zh-TW" },
  { id: "hanzi_common_081", category: "hanzi", display: "糖", hint: "ㄊㄤˊ", pinyin: "táng", meaning: "sugar / candy", speakText: "糖", lang: "zh-TW" },
  { id: "hanzi_common_082", category: "hanzi", display: "鹽", hint: "ㄧㄢˊ", pinyin: "yán", meaning: "salt", speakText: "鹽", lang: "zh-TW" },
  { id: "hanzi_common_083", category: "hanzi", display: "香", hint: "ㄒㄧㄤ", pinyin: "xiāng", meaning: "fragrant", speakText: "香", lang: "zh-TW" },
  { id: "hanzi_common_084", category: "hanzi", display: "甜", hint: "ㄊㄧㄢˊ", pinyin: "tián", meaning: "sweet", speakText: "甜", lang: "zh-TW" },
  { id: "hanzi_common_085", category: "hanzi", display: "酸", hint: "ㄙㄨㄢ", pinyin: "suān", meaning: "sour", speakText: "酸", lang: "zh-TW" },
  { id: "hanzi_common_086", category: "hanzi", display: "苦", hint: "ㄎㄨˇ", pinyin: "kǔ", meaning: "bitter", speakText: "苦", lang: "zh-TW" },
  { id: "hanzi_common_087", category: "hanzi", display: "零", hint: "ㄌㄧㄥˊ", pinyin: "líng", meaning: "zero", speakText: "零", lang: "zh-TW" },
  { id: "hanzi_common_088", category: "hanzi", display: "半", hint: "ㄅㄢˋ", pinyin: "bàn", meaning: "half", speakText: "半", lang: "zh-TW" },
  { id: "hanzi_common_089", category: "hanzi", display: "次", hint: "ㄘˋ", pinyin: "cì", meaning: "time / instance", speakText: "次", lang: "zh-TW" },
  { id: "hanzi_common_090", category: "hanzi", display: "回", hint: "ㄏㄨㄟˊ", pinyin: "huí", meaning: "return / time", speakText: "回", lang: "zh-TW" },
  { id: "hanzi_common_091", category: "hanzi", display: "步", hint: "ㄅㄨˋ", pinyin: "bù", meaning: "step", speakText: "步", lang: "zh-TW" },
  { id: "hanzi_common_092", category: "hanzi", display: "件", hint: "ㄐㄧㄢˋ", pinyin: "jiàn", meaning: "item measure word", speakText: "件", lang: "zh-TW" },
  { id: "hanzi_common_093", category: "hanzi", display: "位", hint: "ㄨㄟˋ", pinyin: "wèi", meaning: "position / polite measure word", speakText: "位", lang: "zh-TW" },
  { id: "hanzi_common_094", category: "hanzi", display: "張", hint: "ㄓㄤ", pinyin: "zhāng", meaning: "sheet measure word", speakText: "張", lang: "zh-TW" },
  { id: "hanzi_common_095", category: "hanzi", display: "隻", hint: "ㄓ", pinyin: "zhī", meaning: "animal measure word", speakText: "隻", lang: "zh-TW" },
  { id: "hanzi_common_096", category: "hanzi", display: "條", hint: "ㄊㄧㄠˊ", pinyin: "tiáo", meaning: "strip measure word", speakText: "條", lang: "zh-TW" },
  { id: "hanzi_common_097", category: "hanzi", display: "枝", hint: "ㄓ", pinyin: "zhī", meaning: "branch / stick measure word", speakText: "枝", lang: "zh-TW" },
  { id: "hanzi_common_098", category: "hanzi", display: "顆", hint: "ㄎㄜ", pinyin: "kē", meaning: "small round measure word", speakText: "顆", lang: "zh-TW" },
  { id: "hanzi_common_099", category: "hanzi", display: "北", hint: "ㄅㄟˇ", pinyin: "běi", meaning: "north", speakText: "北", lang: "zh-TW" },
  { id: "hanzi_common_100", category: "hanzi", display: "南", hint: "ㄋㄢˊ", pinyin: "nán", meaning: "south", speakText: "南", lang: "zh-TW" },
  { id: "hanzi_common_101", category: "hanzi", display: "東", hint: "ㄉㄨㄥ", pinyin: "dōng", meaning: "east", speakText: "東", lang: "zh-TW" },
  { id: "hanzi_common_102", category: "hanzi", display: "西", hint: "ㄒㄧ", pinyin: "xī", meaning: "west", speakText: "西", lang: "zh-TW" },
  { id: "hanzi_common_103", category: "hanzi", display: "旁", hint: "ㄆㄤˊ", pinyin: "páng", meaning: "beside", speakText: "旁", lang: "zh-TW" },
  { id: "hanzi_common_104", category: "hanzi", display: "邊", hint: "ㄅㄧㄢ", pinyin: "biān", meaning: "side / edge", speakText: "邊", lang: "zh-TW" },
  { id: "hanzi_common_105", category: "hanzi", display: "村", hint: "ㄘㄨㄣ", pinyin: "cūn", meaning: "village", speakText: "村", lang: "zh-TW" },
  { id: "hanzi_common_106", category: "hanzi", display: "里", hint: "ㄌㄧˇ", pinyin: "lǐ", meaning: "inside / neighborhood", speakText: "里", lang: "zh-TW" },
  { id: "hanzi_common_107", category: "hanzi", display: "鄉", hint: "ㄒㄧㄤ", pinyin: "xiāng", meaning: "township / hometown", speakText: "鄉", lang: "zh-TW" },
  { id: "hanzi_common_108", category: "hanzi", display: "鎮", hint: "ㄓㄣˋ", pinyin: "zhèn", meaning: "town", speakText: "鎮", lang: "zh-TW" },
  { id: "hanzi_common_109", category: "hanzi", display: "縣", hint: "ㄒㄧㄢˋ", pinyin: "xiàn", meaning: "county", speakText: "縣", lang: "zh-TW" },
  { id: "hanzi_common_110", category: "hanzi", display: "區", hint: "ㄑㄩ", pinyin: "qū", meaning: "district", speakText: "區", lang: "zh-TW" },
  { id: "hanzi_common_111", category: "hanzi", display: "頭", hint: "ㄊㄡˊ", pinyin: "tóu", meaning: "head", speakText: "頭", lang: "zh-TW" },
  { id: "hanzi_common_112", category: "hanzi", display: "眼", hint: "ㄧㄢˇ", pinyin: "yǎn", meaning: "eye", speakText: "眼", lang: "zh-TW" },
  { id: "hanzi_common_113", category: "hanzi", display: "鼻", hint: "ㄅㄧˊ", pinyin: "bí", meaning: "nose", speakText: "鼻", lang: "zh-TW" },
  { id: "hanzi_common_114", category: "hanzi", display: "牙", hint: "ㄧㄚˊ", pinyin: "yá", meaning: "tooth", speakText: "牙", lang: "zh-TW" },
  { id: "hanzi_common_115", category: "hanzi", display: "臉", hint: "ㄌㄧㄢˇ", pinyin: "liǎn", meaning: "face", speakText: "臉", lang: "zh-TW" },
  { id: "hanzi_common_116", category: "hanzi", display: "身", hint: "ㄕㄣ", pinyin: "shēn", meaning: "body", speakText: "身", lang: "zh-TW" },
  { id: "hanzi_common_117", category: "hanzi", display: "體", hint: "ㄊㄧˇ", pinyin: "tǐ", meaning: "body / form", speakText: "體", lang: "zh-TW" },
  { id: "hanzi_common_118", category: "hanzi", display: "腳", hint: "ㄐㄧㄠˇ", pinyin: "jiǎo", meaning: "foot", speakText: "腳", lang: "zh-TW" },
  { id: "hanzi_common_119", category: "hanzi", display: "腿", hint: "ㄊㄨㄟˇ", pinyin: "tuǐ", meaning: "leg", speakText: "腿", lang: "zh-TW" },
  { id: "hanzi_common_120", category: "hanzi", display: "衣", hint: "ㄧ", pinyin: "yī", meaning: "clothes", speakText: "衣", lang: "zh-TW" },
  { id: "hanzi_common_121", category: "hanzi", display: "帽", hint: "ㄇㄠˋ", pinyin: "mào", meaning: "hat", speakText: "帽", lang: "zh-TW" },
  { id: "hanzi_common_122", category: "hanzi", display: "鞋", hint: "ㄒㄧㄝˊ", pinyin: "xié", meaning: "shoe", speakText: "鞋", lang: "zh-TW" },
  { id: "hanzi_common_123", category: "hanzi", display: "拿", hint: "ㄋㄚˊ", pinyin: "ná", meaning: "take / hold", speakText: "拿", lang: "zh-TW" },
  { id: "hanzi_common_124", category: "hanzi", display: "放", hint: "ㄈㄤˋ", pinyin: "fàng", meaning: "put / release", speakText: "放", lang: "zh-TW" },
  { id: "hanzi_common_125", category: "hanzi", display: "找", hint: "ㄓㄠˇ", pinyin: "zhǎo", meaning: "look for", speakText: "找", lang: "zh-TW" },
  { id: "hanzi_common_126", category: "hanzi", display: "告", hint: "ㄍㄠˋ", pinyin: "gào", meaning: "tell", speakText: "告", lang: "zh-TW" },
  { id: "hanzi_common_127", category: "hanzi", display: "訴", hint: "ㄙㄨˋ", pinyin: "sù", meaning: "tell / complain", speakText: "訴", lang: "zh-TW" },
  { id: "hanzi_common_128", category: "hanzi", display: "洗", hint: "ㄒㄧˇ", pinyin: "xǐ", meaning: "wash", speakText: "洗", lang: "zh-TW" },
  { id: "hanzi_common_129", category: "hanzi", display: "刷", hint: "ㄕㄨㄚ", pinyin: "shuā", meaning: "brush", speakText: "刷", lang: "zh-TW" },
  { id: "hanzi_common_130", category: "hanzi", display: "穿", hint: "ㄔㄨㄢ", pinyin: "chuān", meaning: "wear / pass through", speakText: "穿", lang: "zh-TW" },
  { id: "hanzi_common_131", category: "hanzi", display: "脫", hint: "ㄊㄨㄛ", pinyin: "tuō", meaning: "take off", speakText: "脫", lang: "zh-TW" },
  { id: "hanzi_common_132", category: "hanzi", display: "起", hint: "ㄑㄧˇ", pinyin: "qǐ", meaning: "rise / start", speakText: "起", lang: "zh-TW" },
  { id: "hanzi_common_133", category: "hanzi", display: "睡", hint: "ㄕㄨㄟˋ", pinyin: "shuì", meaning: "sleep", speakText: "睡", lang: "zh-TW" },
  { id: "hanzi_common_134", category: "hanzi", display: "醒", hint: "ㄒㄧㄥˇ", pinyin: "xǐng", meaning: "wake up", speakText: "醒", lang: "zh-TW" },
  { id: "hanzi_common_135", category: "hanzi", display: "休", hint: "ㄒㄧㄡ", pinyin: "xiū", meaning: "rest", speakText: "休", lang: "zh-TW" },
  { id: "hanzi_common_136", category: "hanzi", display: "息", hint: "ㄒㄧˊ", pinyin: "xí", meaning: "rest / breath", speakText: "息", lang: "zh-TW" },
  { id: "hanzi_common_137", category: "hanzi", display: "忙", hint: "ㄇㄤˊ", pinyin: "máng", meaning: "busy", speakText: "忙", lang: "zh-TW" },
  { id: "hanzi_common_138", category: "hanzi", display: "幫", hint: "ㄅㄤ", pinyin: "bāng", meaning: "help", speakText: "幫", lang: "zh-TW" },
  { id: "hanzi_common_139", category: "hanzi", display: "送", hint: "ㄙㄨㄥˋ", pinyin: "sòng", meaning: "send", speakText: "送", lang: "zh-TW" },
  { id: "hanzi_common_140", category: "hanzi", display: "收", hint: "ㄕㄡ", pinyin: "shōu", meaning: "receive / collect", speakText: "收", lang: "zh-TW" },
  { id: "hanzi_common_141", category: "hanzi", display: "等", hint: "ㄉㄥˇ", pinyin: "děng", meaning: "wait / etc.", speakText: "等", lang: "zh-TW" },
  { id: "hanzi_common_142", category: "hanzi", display: "記", hint: "ㄐㄧˋ", pinyin: "jì", meaning: "remember / record", speakText: "記", lang: "zh-TW" },
  { id: "hanzi_common_143", category: "hanzi", display: "忘", hint: "ㄨㄤˋ", pinyin: "wàng", meaning: "forget", speakText: "忘", lang: "zh-TW" },
  { id: "hanzi_common_144", category: "hanzi", display: "快", hint: "ㄎㄨㄞˋ", pinyin: "kuài", meaning: "fast / happy", speakText: "快", lang: "zh-TW" },
  { id: "hanzi_common_145", category: "hanzi", display: "慢", hint: "ㄇㄢˋ", pinyin: "màn", meaning: "slow", speakText: "慢", lang: "zh-TW" },
  { id: "hanzi_common_146", category: "hanzi", display: "遠", hint: "ㄩㄢˇ", pinyin: "yuǎn", meaning: "far", speakText: "遠", lang: "zh-TW" },
  { id: "hanzi_common_147", category: "hanzi", display: "近", hint: "ㄐㄧㄣˋ", pinyin: "jìn", meaning: "near", speakText: "近", lang: "zh-TW" },
  { id: "hanzi_common_148", category: "hanzi", display: "重", hint: "ㄓㄨㄥˋ", pinyin: "zhòng", meaning: "heavy / important", speakText: "重", lang: "zh-TW" },
  { id: "hanzi_common_149", category: "hanzi", display: "輕", hint: "ㄑㄧㄥ", pinyin: "qīng", meaning: "light", speakText: "輕", lang: "zh-TW" },
  { id: "hanzi_common_150", category: "hanzi", display: "強", hint: "ㄑㄧㄤˊ", pinyin: "qiáng", meaning: "strong", speakText: "強", lang: "zh-TW" },
  ];
  window.BulaTeachLessonData = {
    ...(window.BulaTeachLessonData || {}),
    hanzi: lessons
  };
})();
