const ids=["difficultyScreen","questionScreen","backButton","speakButton","difficultyLabel","modeBadge","passage","prompt","answerGrid","feedback","feedbackTitle","feedbackText","nextButton"];
const el=Object.fromEntries(ids.map(id=>[id,document.getElementById(id)]));
const LEVELS={easy:{label:"簡單",makers:[makeShopping,makeCompare,makeSequence]},medium:{label:"中等",makers:[makeShopping,makeTime,makeSequence,makeTruth]},hard:{label:"困難",makers:[makeShopping,makeTime,makeSequence,makeTruth,makeLogic]}};
let level="easy",current=null,answered=false;
function rand(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function pick(a){return a[rand(0,a.length-1)]}
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=rand(0,i);[a[i],a[j]]=[a[j],a[i]]}return a}
function makeChoices(answer,wrong){const correct=String(answer),others=wrong.map(String).filter((x,i,a)=>x!==correct&&a.indexOf(x)===i);return shuffle([correct,...shuffle(others).slice(0,3)])}
function numericChoices(n,unit=""){return makeChoices(n+unit,[n-1,n+1,n+2,n+5].filter(x=>x>=0).map(x=>x+unit))}
function task(mode,text,question,answer,choices,explanation){return{mode,text,question,answer:String(answer),choices,explanation}}
function makeShopping(difficulty){const name=pick(["小安","小美","子晴","阿哲"]),item=pick(["鉛筆","橡皮擦","貼紙","筆記本"]),price=rand(4,difficulty==="easy"?12:18),count=rand(2,difficulty==="hard"?6:4),cost=price*count;if(difficulty==="easy")return task("購物任務",`${name}買了 ${count} 個每個 ${price} 元的${item}。`,`一共要付多少元？`,cost+" 元",numericChoices(cost," 元"),`${price} × ${count} ＝ ${cost}。`);const extra=rand(5,15),paid=Math.ceil((cost+extra)/10)*10,change=paid-cost;return task("購物任務",`${name}買了 ${count} 個每個 ${price} 元的${item}，付了 ${paid} 元。`,`可以找回多少元？`,change+" 元",numericChoices(change," 元"),`${price} × ${count} ＝ ${cost}，${paid} － ${cost} ＝ ${change}。`)}
function makeCompare(){const names=shuffle(["小安","小美","小華"]),a=rand(4,10),b=a+rand(2,5);return task("比較線索",`${names[0]}有 ${a} 枝筆。${names[1]}有 ${b} 枝筆。`,`誰的筆比較多？`,names[1],shuffle([names[0],names[1],names[2],"一樣多"]),`${b} 比 ${a} 大，所以答案是${names[1]}。`)}
function formatTime(minutes){return `下午 ${Math.floor(minutes/60)}:${String(minutes%60).padStart(2,"0")}`}
function makeTime(difficulty){const name=pick(["小安","小美","小華"]),start=rand(1,4)*60+pick([0,10,20,30]),duration=difficulty==="hard"?pick([45,50,70,80]):pick([20,30,40]),end=start+duration;return task("時間任務",`${name}在${formatTime(start)}開始閱讀，讀了 ${duration} 分鐘。`,`幾點讀完？`,formatTime(end),makeChoices(formatTime(end),[formatTime(end-10),formatTime(end+10),formatTime(end+20)]),`${formatTime(start)}加上 ${duration} 分鐘，就是${formatTime(end)}。`)}
function makeSequence(difficulty){const names=shuffle(["小安","小美","小華",...(difficulty==="hard"?["子晴"]:[])]),sentences=[];for(let i=0;i<names.length-1;i++)sentences.push(`${names[i]}排在${names[i+1]}前面。`);return task("順序推理",sentences.join("\n"),"誰排在最前面？",names[0],shuffle(names),`依照前後線索排列，最前面是${names[0]}。`)}
function makeTruth(){const a=rand(6,15),more=rand(2,6),b=a+more,name1=pick(["小安","小華"]),name2=pick(["小美","子晴"]),answer=`${name2}比${name1}多 ${more} 個。`;return task("真假判斷",`${name1}有 ${a} 個積木，${name2}有 ${b} 個積木。`,`哪一句話正確？`,answer,shuffle([answer,`${name1}比${name2}多。`,"兩人一樣多。","無法知道。"]),`${b} － ${a} ＝ ${more}，所以${answer}`)}
function makeLogic(){const names=shuffle(["小安","小美","小華"]),items=shuffle(["蘋果","香蕉","橘子"]),answer=`${names[2]}拿${items[2]}`;return task("條件推理",`${names[0]}拿的不是${items[1]}，而是${items[0]}。\n${names[1]}拿了${items[1]}。\n每個人拿不同的水果。`,`${names[2]}拿了什麼？`,answer,shuffle(items.map(item=>`${names[2]}拿${item}`).concat("無法確定")),`${items[0]}和${items[1]}已經有人拿了，所以${answer}。`)}
function newQuestion(){const config=LEVELS[level];current=pick(config.makers)(level);answered=false;el.difficultyLabel.textContent=config.label;el.modeBadge.textContent=current.mode;el.passage.textContent=current.text;el.prompt.textContent=current.question;el.answerGrid.textContent="";el.feedback.classList.add("is-hidden");el.nextButton.classList.add("is-hidden");current.choices.forEach(value=>{const button=document.createElement("button");button.type="button";button.className="answer-button";button.textContent=value;button.addEventListener("click",()=>answer(button,value));el.answerGrid.append(button)})}
function answer(button,value){if(answered)return;answered=true;const correct=value===current.answer;el.answerGrid.querySelectorAll("button").forEach(item=>{item.disabled=true;if(item.textContent===current.answer)item.classList.add("is-correct")});if(!correct)button.classList.add("is-wrong");el.feedbackTitle.textContent=correct?"答對了！":`答錯了，正確答案是「${current.answer}」。`;el.feedbackText.textContent=current.explanation;el.feedback.classList.remove("is-hidden");el.nextButton.classList.remove("is-hidden")}
function speak(){if(!current||!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(`${current.text}。${current.question}`);utterance.lang="zh-TW";utterance.rate=.85;window.speechSynthesis.speak(utterance)}
document.querySelectorAll("[data-level]").forEach(button=>button.addEventListener("click",()=>{level=button.dataset.level;el.difficultyScreen.classList.add("is-hidden");el.questionScreen.classList.remove("is-hidden");newQuestion()}));
el.backButton.addEventListener("click",()=>{if("speechSynthesis" in window)window.speechSynthesis.cancel();el.questionScreen.classList.add("is-hidden");el.difficultyScreen.classList.remove("is-hidden")});
el.speakButton.addEventListener("click",speak);el.nextButton.addEventListener("click",newQuestion);
